version: '3.9'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sadiasbs
      POSTGRES_DB: notificationsdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "5436:5432"  # Exposing Postgres on port 5434
    networks:
      - notification-network

  notification-service:
    build: .
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: sadiasbs
      PG_DATABASE: notificationsdb
    depends_on:
      - postgres
    ports:
      - "5004:5004"
    networks:
      - notification-network

networks:
  notification-network:
    driver: bridge
