version: '3'
services:
  # PostgreSQL service
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sadiasbs
      POSTGRES_DB: bcf
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data  # Persist data
      - ./db-init:/docker-entrypoint-initdb.d  # Initialize with SQL scripts
    restart: always  # Auto-restart the service if it fails

  # Train Service (Node.js)
  train-service:
    build: .
    ports:
      - "5000:5000"  # Expose the Train Service on port 5000
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: sadiasbs
      PG_DATABASE: bcf
    depends_on:
      - postgres  # Ensure PostgreSQL starts first
    working_dir: /usr/src/app  # Ensure correct working directory for Node.js
    restart: always  # Auto-restart the service if it fails
