version: '3'
services:
  # PostgreSQL service for Train and Auth Services
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sadiasbs
      POSTGRES_DB: bcf  # Your existing database
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data  # Persist data
      - ./db-init:/docker-entrypoint-initdb.d  # Initialize with SQL scripts
    restart: always  # Auto-restart the service if it fails
  auth-service:
    build: .  # Path to the auth-service
    ports:
      - "5001:5001"  # Expose the Auth Service on port 5001
    environment:
      PG_HOST: postgres  # Connect to the existing Postgres service
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: sadiasbs
      PG_DATABASE: bcf  # Your existing database
      JWT_SECRET: yourSuperSecretJWTKey
    depends_on:
      - postgres  # Ensure PostgreSQL starts first
    working_dir: /usr/src/app  # Ensure correct working directory for Node.js
    restart: always  # Auto-restart the service if it fails