version: '3'
services:
  # PostgreSQL service for Ticket Service and other services
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sadiasbs
      POSTGRES_DB: ticket
    ports:
      - "5434:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    restart: always

  # Ticket Service (Node.js)
  ticket-service:
    build: .
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: sadiasbs
      PG_DATABASE: ticket
    ports:
      - "5002:5002"
    depends_on:
      - postgres
    restart: always
