version: '3'

services:
  # PostgreSQL database service
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sadiasbs
      POSTGRES_DB: payments
    ports:
      - "5437:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

    networks:
      - payment-network

  # Payment service (Node.js)
  payment-service:
    build: .
    ports:
      - "5005:5005"
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: sadiasbss
      PG_DATABASE: payments
    depends_on:
      - postgres
    networks:
      - payment-network

networks:
  payment-network:
    driver: bridge
