version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sadiasbs
      POSTGRES_DB: booking_service
    ports:
      - "5435:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d 
    networks:
      - booking-network

  booking-service:
    build: .
    ports:
      - "5003:5003"
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: sadiasbs
      PG_DATABASE: booking_service
    depends_on:
      - postgres
    networks:
      - booking-network

networks:
  booking-network:
    driver: bridge
